spring:
  application:
    name: eureka-server
 # cloud:
  #  config:
   #   enabled: true
    #  label: master
     # uri: ${CONFIG_SERVER_URI}
  cloud:
    config:
      enabled: true
      uri: http://localhost:7000    
  banner:
    location: classpath:banner/banner.txt
    image:
     location: classpath:fotocreador/egardengo.jpeg 